from enum import Enum, auto

class TokenType(Enum):
    ID = auto()

    ASSIGN_OPERATOR = auto()
    AND_OPERATOR = auto()
    OR_OPERATOR = auto()
    ADD_OPERATOR = auto()
    SUB_OPERATOR = auto()
    MUL_OPERATOR = auto()
    MUL_OPRATOR = auto()
    DIV_OPERATOR = auto()
    LAMBDA_ID = auto()
    NEGATION_OPERATOR = auto()
    EQUAL_OPERATOR = auto()
    NOT_EQUAL_OPERATOR = auto()
    LESS_THAN_OPERATOR = auto()
    GREATER_THAN_OPERATOR = auto()
    LESS_OR_EQUAL_THAN_OPERATOR = auto()
    GREATER_OR_EQUAL_THAN_OPERATOR = auto()
    LAMBDA_OPERATOR = auto()
    COMMENT = auto()

    INT_VALUE = auto()
    FLOAT_VALUE = auto()
    STRING_VALUE = auto()
    TRUE_VALUE = auto()
    FALSE_VALUE = auto()
    LIST_VALUE = auto()

    LEFT_BRACKET = auto()
    RIGHT_BRACKET = auto()
    LEFT_CURLY_BRACKET = auto()
    RIGHT_CURLY_BRACKET = auto()
    LEFT_QUADRATIC_BRACKET = auto()
    RIGHT_QUADRATIC_BRACKET = auto()
    COMMA = auto()
    SEMICOLON = auto()
    DOT = auto()
    IF_NAME = auto()
    ELSE_NAME = auto()
    WHILE_NAME = auto()
    BREAK_NAME = auto()
    RETURN_NAME = auto()
    FROM_NAME = auto()
    IMPORT_NAME = auto()
    DEF = auto()
    EOF = auto()